// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIrncfs14KUaEz_0RCLsZM5ZXzfCIhurY',
    appId: '1:450721366813:web:8c38698cacd8b1763057f4',
    messagingSenderId: '450721366813',
    projectId: 'flutter-chat-app-b2b1b',
    authDomain: 'flutter-chat-app-b2b1b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b2b1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_mblKdY95tn4sofvCNSSSAAl3j2K2vQ',
    appId: '1:450721366813:android:3da6c68aed7cd77e3057f4',
    messagingSenderId: '450721366813',
    projectId: 'flutter-chat-app-b2b1b',
    storageBucket: 'flutter-chat-app-b2b1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA54SVApE84SCCKZ2FNksmoHcjt1jRhWH8',
    appId: '1:450721366813:ios:2671a538b329418b3057f4',
    messagingSenderId: '450721366813',
    projectId: 'flutter-chat-app-b2b1b',
    storageBucket: 'flutter-chat-app-b2b1b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIrncfs14KUaEz_0RCLsZM5ZXzfCIhurY',
    appId: '1:450721366813:web:89aacc5aa0be52e93057f4',
    messagingSenderId: '450721366813',
    projectId: 'flutter-chat-app-b2b1b',
    authDomain: 'flutter-chat-app-b2b1b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b2b1b.appspot.com',
  );

}